### ISSUE TITLE
求助，无法运行

### ISSUE THREAD

**Issue by NekoAndLoli** [cyanray/mirai-cpp-template#3]
提示：Please select a valid startup
怎么办？

**Comment by cyanray** [comment]
很抱歉才看到。
你要在 Visual Studio 中选择要启动的项目(my-qqrobot)。
![](https://docs.microsoft.com/en-us/cpp/build/media/cmake-run-button.png?view=msvc-160)
参考文献：https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-160
